# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet_analysis', '0002_reliability_names_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliability_names_results',
            name='author_type_alpha',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='author_type_percent',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='author_type_pi',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
    ]
