# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_analysis', '0005_auto_20160304_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliability_names_results',
            name='author_type_non_zero_alpha',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='author_type_non_zero_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='author_type_non_zero_percent',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='author_type_non_zero_pi',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
    ]
