# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context_analysis', '0006_auto_20160304_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reliability_names_results',
            old_name='author_combined_alpha',
            new_name='author_lookup_combined_alpha',
        ),
        migrations.RenameField(
            model_name='reliability_names_results',
            old_name='author_combined_percent',
            new_name='author_lookup_combined_percent',
        ),
        migrations.RenameField(
            model_name='reliability_names_results',
            old_name='author_lookup_alpha',
            new_name='author_lookup_non_zero_alpha',
        ),
        migrations.RenameField(
            model_name='reliability_names_results',
            old_name='author_lookup_count',
            new_name='author_lookup_non_zero_count',
        ),
        migrations.RenameField(
            model_name='reliability_names_results',
            old_name='author_lookup_percent',
            new_name='author_lookup_non_zero_percent',
        ),
        migrations.RenameField(
            model_name='reliability_names_results',
            old_name='subject_combined_alpha',
            new_name='subject_lookup_combined_alpha',
        ),
        migrations.RenameField(
            model_name='reliability_names_results',
            old_name='subject_combined_percent',
            new_name='subject_lookup_combined_percent',
        ),
        migrations.RenameField(
            model_name='reliability_names_results',
            old_name='subject_lookup_alpha',
            new_name='subject_lookup_non_zero_alpha',
        ),
        migrations.RenameField(
            model_name='reliability_names_results',
            old_name='subject_lookup_count',
            new_name='subject_lookup_non_zero_count',
        ),
        migrations.RenameField(
            model_name='reliability_names_results',
            old_name='subject_lookup_percent',
            new_name='subject_lookup_non_zero_percent',
        ),
    ]
