# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 22:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('context_analysis', '0008_auto_20160314_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reliability_Names_Coder_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coder_numeric_id', models.IntegerField(blank=True, null=True)),
                ('detected', models.IntegerField(blank=True, null=True)),
                ('person_id', models.IntegerField(blank=True, null=True)),
                ('person_type', models.CharField(blank=True, max_length=255, null=True)),
                ('person_type_int', models.IntegerField(blank=True, null=True)),
                ('article_data_id', models.IntegerField(blank=True, null=True)),
                ('article_person_id', models.IntegerField(blank=True, null=True)),
                ('first_quote_graph', models.IntegerField(blank=True, null=True)),
                ('first_quote_index', models.IntegerField(blank=True, null=True)),
                ('organization_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('coder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reliability_names', 'coder'],
            },
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder10_first_quote_graf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder10_first_quote_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder10_organization_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder1_first_quote_graf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder1_first_quote_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder1_organization_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder2_first_quote_graf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder2_first_quote_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder2_organization_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder3_first_quote_graf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder3_first_quote_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder3_organization_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder4_first_quote_graf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder4_first_quote_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder4_organization_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder5_first_quote_graf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder5_first_quote_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder5_organization_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder6_first_quote_graf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder6_first_quote_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder6_organization_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder7_first_quote_graf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder7_first_quote_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder7_organization_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder8_first_quote_graf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder8_first_quote_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder8_organization_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder9_first_quote_graf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder9_first_quote_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='coder9_organization_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_coder_data',
            name='reliability_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='context_analysis.Reliability_Names'),
        ),
    ]
