# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('context_analysis', '0009_auto_20160323_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field_Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(blank=True, max_length=255, null=True)),
                ('measurement_level', models.CharField(blank=True, max_length=255, null=True)),
                ('value_count', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Field_Spec_Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('field_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_analysis.Field_Spec')),
            ],
        ),
        migrations.CreateModel(
            name='Reliability_Result_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comparison_value', models.CharField(blank=True, max_length=255, null=True)),
                ('case_count', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('field_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_analysis.Field_Spec')),
            ],
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='subject_first_quote_graf_alpha',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='subject_first_quote_graf_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='subject_first_quote_graf_percent',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='subject_first_quote_graf_pi',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='subject_first_quote_index_alpha',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='subject_first_quote_index_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='subject_first_quote_index_percent',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='subject_first_quote_index_pi',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='subject_organization_hash_alpha',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='subject_organization_hash_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='subject_organization_hash_percent',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names_results',
            name='subject_organization_hash_pi',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='reliability_result_details',
            name='reliability_names_results',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_analysis.Reliability_Names_Results'),
        ),
    ]
