# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet_analysis', '0010_auto_20160324_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='field_spec',
            name='integer_base',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field_spec',
            name='truncate_from',
            field=models.CharField(blank=True, choices=[('left', 'Chop from left'), ('right', 'Chop from right')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='field_spec',
            name='truncate_to_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='field_spec',
            name='data_type',
            field=models.CharField(blank=True, choices=[('integer', 'Integer'), ('decimal', 'Decimal'), ('hex_hash', 'Hexadecimal Hash'), ('string', 'String')], max_length=255, null=True),
        ),
    ]
