# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet_analysis', '0011_auto_20160718_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliability_names',
            name='person_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliability_names',
            name='person_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
