# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context_analysis', '0012_auto_20160804_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reliability_names',
            options={'ordering': ['article', 'person_type', 'person_last_name', 'person_first_name', 'person_name', 'person']},
        ),
    ]
