# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_analysis', '0016_auto_20170703_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='event_type',
            field=models.CharField(blank=True, choices=[('delete', 'delete'), ('merge', 'merge'), ('add_tags', 'add tags'), ('remove_tags', 'remove tags')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reliability_names_evaluation',
            name='persons',
            field=models.ManyToManyField(blank=True, to='context_text.Person'),
        ),
        migrations.AlterField(
            model_name='reliability_names_evaluation',
            name='status',
            field=models.CharField(blank=True, choices=[('CORRECT', 'CORRECT'), ('ERROR', 'ERROR'), ('INCOMPLETE', 'INCOMPLETE')], max_length=255, null=True),
        ),
    ]
