# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet_analysis', '0017_auto_20170708_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reliability_names_evaluation',
            old_name='merged_from_id',
            new_name='merged_from_reliability_names_id',
        ),
        migrations.RenameField(
            model_name='reliability_names_evaluation',
            old_name='merged_to_id',
            new_name='merged_to_reliability_names_id',
        ),
    ]
