# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet_analysis', '0020_reliability_names_evaluation_is_single_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliability_names_evaluation',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcenet.Article'),
        ),
        migrations.AlterField(
            model_name='reliability_names_evaluation',
            name='reliability_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcenet_analysis.Reliability_Names'),
        ),
    ]
