# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_analysis', '0021_auto_20170727_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reliability_names_evaluation',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_ambiguous',
            field=models.BooleanField(default=False),
        ),
    ]
