# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet_analysis', '0024_auto_20170730_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_mentioned_shb_quoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_quoted_shb_mentioned',
            field=models.BooleanField(default=False),
        ),
    ]
