# Generated by Django 2.0.1 on 2018-01-27 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet_analysis', '0026_reliability_names_evaluation_is_not_hard_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_a_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_a_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_author_shb_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_missed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_not_a_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_source_shb_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_to_do',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_wrong_text_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='work_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reliability_names',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sourcenet.Article'),
        ),
        migrations.AlterField(
            model_name='reliability_names',
            name='coder1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_names_coder1_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_names',
            name='coder10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_names_coder10_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_names',
            name='coder2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_names_coder2_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_names',
            name='coder3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_names_coder3_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_names',
            name='coder4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_names_coder4_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_names',
            name='coder5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_names_coder5_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_names',
            name='coder6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_names_coder6_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_names',
            name='coder7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_names_coder7_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_names',
            name='coder8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_names_coder8_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_names',
            name='coder9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_names_coder9_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_names',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sourcenet.Person'),
        ),
        migrations.AlterField(
            model_name='reliability_names_coder_data',
            name='coder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_names_results',
            name='coder1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_names_results_coder1_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_names_results',
            name='coder2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_names_results_coder2_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_ties',
            name='coder1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_ties_coder1_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_ties',
            name='coder10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_ties_coder10_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_ties',
            name='coder2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_ties_coder2_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_ties',
            name='coder3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_ties_coder3_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_ties',
            name='coder4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_ties_coder4_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_ties',
            name='coder5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_ties_coder5_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_ties',
            name='coder6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_ties_coder6_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_ties',
            name='coder7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_ties_coder7_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_ties',
            name='coder8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_ties_coder8_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_ties',
            name='coder9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_ties_coder9_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reliability_ties',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_ties_from_set', to='sourcenet.Person'),
        ),
        migrations.AlterField(
            model_name='reliability_ties',
            name='relation_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reliability_ties_to_set', to='sourcenet.Person'),
        ),
    ]
