# Generated by Django 2.0.2 on 2018-02-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet_analysis', '0027_auto_20180127_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reliability_names_evaluation',
            old_name='is_author_shb_source',
            new_name='is_author_shb_subject',
        ),
        migrations.RenameField(
            model_name='reliability_names_evaluation',
            old_name='is_source_shb_author',
            new_name='is_subject_shb_author',
        ),
    ]
