# Generated by Django 2.0.2 on 2018-02-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet_analysis', '0028_auto_20180203_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reliability_names_evaluation',
            old_name='is_missed',
            new_name='is_missed_subject',
        ),
        migrations.AddField(
            model_name='reliability_names_evaluation',
            name='is_missed_author',
            field=models.BooleanField(default=False),
        ),
    ]
