# Generated by Django 3.1.2 on 2020-10-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('context_text', '0032_auto_20191205_0356'),
        ('context_analysis', '0033_remove_reliability_names_evaluation_is_non_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reliability_Names_Evaluation',
            new_name='Reliability_Names_Eval',
        ),
    ]
