UPDATE django_content_type SET app_label='context_analysis' WHERE app_label='sourcenet_analysis';
UPDATE django_migrations SET app='context_analysis' WHERE app='sourcenet_analysis';

/*
-- Get the index names of all the indexes for tables in this application.
--     (and get each twice for ease of making ALTER INDEX statements)
SELECT indexname, indexname
FROM pg_indexes
WHERE tablename LIKE 'sourcenet_analysis_%';
*/

ALTER INDEX sourcenet_analysis_field_spec_pkey RENAME TO context_analysis_field_spec_pkey;
ALTER INDEX sourcenet_analysis_field_spec_value_pkey RENAME TO context_analysis_field_spec_value_pkey;
ALTER INDEX sourcenet_analysis_relia_reliability_names_evalua_1f43d507_uniq RENAME TO context_analysis_relia_reliability_names_evalua_1f43d507_uniq;
ALTER INDEX sourcenet_analysis_relia_reliability_names_evalua_59a52235_uniq RENAME TO context_analysis_relia_reliability_names_evalua_59a52235_uniq;
ALTER INDEX sourcenet_analysis_relia_reliability_names_evalua_aa75a8e5_uniq RENAME TO context_analysis_relia_reliability_names_evalua_aa75a8e5_uniq;
ALTER INDEX sourcenet_analysis_relia_reliability_names_evalua_fca8325b_uniq RENAME TO context_analysis_relia_reliability_names_evalua_fca8325b_uniq;
ALTER INDEX sourcenet_analysis_reliability_names_coder_data_pkey RENAME TO context_analysis_reliability_names_coder_data_pkey;
ALTER INDEX sourcenet_analysis_reliability_names_evaluation_article_da_pkey RENAME TO context_analysis_reliability_names_evaluation_article_da_pkey;
ALTER INDEX sourcenet_analysis_reliability_names_evaluation_merged_fro_pkey RENAME TO context_analysis_reliability_names_evaluation_merged_fro_pkey;
ALTER INDEX sourcenet_analysis_reliability_names_evaluation_merged_to__pkey RENAME TO context_analysis_reliability_names_evaluation_merged_to__pkey;
ALTER INDEX sourcenet_analysis_reliability_names_evaluation_persons_pkey RENAME TO context_analysis_reliability_names_evaluation_persons_pkey;
ALTER INDEX sourcenet_analysis_reliability_names_evaluation_pkey RENAME TO context_analysis_reliability_names_evaluation_pkey;
ALTER INDEX sourcenet_analysis_reliability_names_pkey RENAME TO context_analysis_reliability_names_pkey;
ALTER INDEX sourcenet_analysis_reliability_names_results_pkey RENAME TO context_analysis_reliability_names_results_pkey;
ALTER INDEX sourcenet_analysis_reliability_result_details_pkey RENAME TO context_analysis_reliability_result_details_pkey;
ALTER INDEX sourcenet_analysis_reliability_ties_pkey RENAME TO context_analysis_reliability_ties_pkey;
ALTER INDEX sourcenet_analysis_field_spec_value_a7c4f83d RENAME TO context_analysis_field_spec_value_a7c4f83d;
ALTER INDEX sourcenet_analysis_reliabi_article_data_id_aad6541d RENAME TO context_analysis_reliabi_article_data_id_aad6541d;
ALTER INDEX sourcenet_analysis_reliabi_article_data_id_ea941530 RENAME TO context_analysis_reliabi_article_data_id_ea941530;
ALTER INDEX sourcenet_analysis_reliabi_article_data_id_ee0ed8ad RENAME TO context_analysis_reliabi_article_data_id_ee0ed8ad;
ALTER INDEX sourcenet_analysis_reliabi_article_id_67b1e689 RENAME TO context_analysis_reliabi_article_id_67b1e689;
ALTER INDEX sourcenet_analysis_reliabi_person_id_4b52bafc RENAME TO context_analysis_reliabi_person_id_4b52bafc;
ALTER INDEX sourcenet_analysis_reliabi_reliability_names_evaluati_1657c13a RENAME TO context_analysis_reliabi_reliability_names_evaluati_1657c13a;
ALTER INDEX sourcenet_analysis_reliabi_reliability_names_evaluati_b4a812dc RENAME TO context_analysis_reliabi_reliability_names_evaluati_b4a812dc;
ALTER INDEX sourcenet_analysis_reliabi_reliability_names_evaluati_d3151a33 RENAME TO context_analysis_reliabi_reliability_names_evaluati_d3151a33;
ALTER INDEX sourcenet_analysis_reliabi_reliability_names_evaluati_dd3bcb12 RENAME TO context_analysis_reliabi_reliability_names_evaluati_dd3bcb12;
ALTER INDEX sourcenet_analysis_reliabi_reliability_names_id_72c72941 RENAME TO context_analysis_reliabi_reliability_names_id_72c72941;
ALTER INDEX sourcenet_analysis_reliability_names_05bceb54 RENAME TO context_analysis_reliability_names_05bceb54;
ALTER INDEX sourcenet_analysis_reliability_names_0aa713b4 RENAME TO context_analysis_reliability_names_0aa713b4;
ALTER INDEX sourcenet_analysis_reliability_names_0ddb69bd RENAME TO context_analysis_reliability_names_0ddb69bd;
ALTER INDEX sourcenet_analysis_reliability_names_397baa60 RENAME TO context_analysis_reliability_names_397baa60;
ALTER INDEX sourcenet_analysis_reliability_names_3c4842ba RENAME TO context_analysis_reliability_names_3c4842ba;
ALTER INDEX sourcenet_analysis_reliability_names_4adc6a2c RENAME TO context_analysis_reliability_names_4adc6a2c;
ALTER INDEX sourcenet_analysis_reliability_names_5daefa34 RENAME TO context_analysis_reliability_names_5daefa34;
ALTER INDEX sourcenet_analysis_reliability_names_98aa7efd RENAME TO context_analysis_reliability_names_98aa7efd;
ALTER INDEX sourcenet_analysis_reliability_names_a00c1b00 RENAME TO context_analysis_reliability_names_a00c1b00;
ALTER INDEX sourcenet_analysis_reliability_names_a8452ca7 RENAME TO context_analysis_reliability_names_a8452ca7;
ALTER INDEX sourcenet_analysis_reliability_names_coder_data_24c489f2 RENAME TO context_analysis_reliability_names_coder_data_24c489f2;
ALTER INDEX sourcenet_analysis_reliability_names_coder_data_42008789 RENAME TO context_analysis_reliability_names_coder_data_42008789;
ALTER INDEX sourcenet_analysis_reliability_names_da6f4986 RENAME TO context_analysis_reliability_names_da6f4986;
ALTER INDEX sourcenet_analysis_reliability_names_ddbdb868 RENAME TO context_analysis_reliability_names_ddbdb868;
ALTER INDEX sourcenet_analysis_reliability_names_results_05bceb54 RENAME TO context_analysis_reliability_names_results_05bceb54;
ALTER INDEX sourcenet_analysis_reliability_names_results_98aa7efd RENAME TO context_analysis_reliability_names_results_98aa7efd;
ALTER INDEX sourcenet_analysis_reliability_result_details_97b0c32e RENAME TO context_analysis_reliability_result_details_97b0c32e;
ALTER INDEX sourcenet_analysis_reliability_result_details_a7c4f83d RENAME TO context_analysis_reliability_result_details_a7c4f83d;
ALTER INDEX sourcenet_analysis_reliability_ties_05bceb54 RENAME TO context_analysis_reliability_ties_05bceb54;
ALTER INDEX sourcenet_analysis_reliability_ties_0aa713b4 RENAME TO context_analysis_reliability_ties_0aa713b4;
ALTER INDEX sourcenet_analysis_reliability_ties_0ddb69bd RENAME TO context_analysis_reliability_ties_0ddb69bd;
ALTER INDEX sourcenet_analysis_reliability_ties_0ddc6564 RENAME TO context_analysis_reliability_ties_0ddc6564;
ALTER INDEX sourcenet_analysis_reliability_ties_397baa60 RENAME TO context_analysis_reliability_ties_397baa60;
ALTER INDEX sourcenet_analysis_reliability_ties_3c4842ba RENAME TO context_analysis_reliability_ties_3c4842ba;
ALTER INDEX sourcenet_analysis_reliability_ties_4adc6a2c RENAME TO context_analysis_reliability_ties_4adc6a2c;
ALTER INDEX sourcenet_analysis_reliability_ties_5daefa34 RENAME TO context_analysis_reliability_ties_5daefa34;
ALTER INDEX sourcenet_analysis_reliability_ties_98aa7efd RENAME TO context_analysis_reliability_ties_98aa7efd;
ALTER INDEX sourcenet_analysis_reliability_ties_a8452ca7 RENAME TO context_analysis_reliability_ties_a8452ca7;
ALTER INDEX sourcenet_analysis_reliability_ties_da6f4986 RENAME TO context_analysis_reliability_ties_da6f4986;
ALTER INDEX sourcenet_analysis_reliability_ties_ddbdb868 RENAME TO context_analysis_reliability_ties_ddbdb868;

/*
-- Get the table names of all the tables for this application.
--     (and get each twice for ease of making ALTER TABLE statements)
SELECT table_name, table_name
FROM information_schema.tables
WHERE table_name LIKE 'sourcenet_analysis_%'
    AND table_type='BASE TABLE';
*/

ALTER TABLE sourcenet_analysis_reliability_ties RENAME TO context_analysis_reliability_ties;
ALTER TABLE sourcenet_analysis_reliability_result_details RENAME TO context_analysis_reliability_result_details;
ALTER TABLE sourcenet_analysis_reliability_names_results RENAME TO context_analysis_reliability_names_results;
ALTER TABLE sourcenet_analysis_reliability_names_evaluation_persons RENAME TO context_analysis_reliability_names_evaluation_persons;
ALTER TABLE sourcenet_analysis_reliability_names_evaluation_merged_to_a0094 RENAME TO context_analysis_reliability_names_evaluation_merged_to_a0094;
ALTER TABLE sourcenet_analysis_reliability_names_evaluation_merged_fromfd88 RENAME TO context_analysis_reliability_names_evaluation_merged_fromfd88;
ALTER TABLE sourcenet_analysis_reliability_names_evaluation_article_datas RENAME TO context_analysis_reliability_names_evaluation_article_datas;
ALTER TABLE sourcenet_analysis_reliability_names_evaluation RENAME TO context_analysis_reliability_names_evaluation;
ALTER TABLE sourcenet_analysis_reliability_names_coder_data RENAME TO context_analysis_reliability_names_coder_data;
ALTER TABLE sourcenet_analysis_reliability_names RENAME TO context_analysis_reliability_names;
ALTER TABLE sourcenet_analysis_field_spec_value RENAME TO context_analysis_field_spec_value;
ALTER TABLE sourcenet_analysis_field_spec RENAME TO context_analysis_field_spec;

/*
-- Get the sequence names of all the sequences for this application.
--     (and get each twice for ease of making ALTER SEQUENCE statements)
SELECT sequence_name, sequence_name
FROM information_schema.sequences
WHERE sequence_name LIKE 'sourcenet_analysis_%';
*/

ALTER SEQUENCE sourcenet_analysis_reliability_ties_id_seq RENAME TO context_analysis_reliability_ties_id_seq;
ALTER SEQUENCE sourcenet_analysis_reliability_result_details_id_seq RENAME TO context_analysis_reliability_result_details_id_seq;
ALTER SEQUENCE sourcenet_analysis_reliability_names_results_id_seq RENAME TO context_analysis_reliability_names_results_id_seq;
ALTER SEQUENCE sourcenet_analysis_reliability_names_id_seq RENAME TO context_analysis_reliability_names_id_seq;
ALTER SEQUENCE sourcenet_analysis_reliability_names_evaluation_persons_id_seq RENAME TO context_analysis_reliability_names_evaluation_persons_id_seq;
ALTER SEQUENCE sourcenet_analysis_reliability_names_evaluation_merged_t_id_seq RENAME TO context_analysis_reliability_names_evaluation_merged_t_id_seq;
ALTER SEQUENCE sourcenet_analysis_reliability_names_evaluation_merged_f_id_seq RENAME TO context_analysis_reliability_names_evaluation_merged_f_id_seq;
ALTER SEQUENCE sourcenet_analysis_reliability_names_evaluation_id_seq RENAME TO context_analysis_reliability_names_evaluation_id_seq;
ALTER SEQUENCE sourcenet_analysis_reliability_names_evaluation_article__id_seq RENAME TO context_analysis_reliability_names_evaluation_article__id_seq;
ALTER SEQUENCE sourcenet_analysis_reliability_names_coder_data_id_seq RENAME TO context_analysis_reliability_names_coder_data_id_seq;
ALTER SEQUENCE sourcenet_analysis_field_spec_value_id_seq RENAME TO context_analysis_field_spec_value_id_seq;
ALTER SEQUENCE sourcenet_analysis_field_spec_id_seq RENAME TO context_analysis_field_spec_id_seq;
